name: Run tests

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      working-directory: ./django_locallibrary_src/
      run: | 
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      working-directory: ./django_locallibrary_src/
      run: |
        python manage.py test
